### ISSUE TITLE
No localization for id: "err-decryption-failed"

### ISSUE THREAD

**Issue by gpanders** [str4d/rage#159]
## Environment

* OS: macOS
* rage version: 0.5.0

## What were you trying to do

I am using the `age` library crate for an age-based password store. Whenever I trigger a failed decryption (for example, entering the wrong passphrase), the error message that propagates back up to my application is

```
No localization for id: "err-decryption-failed"
```

I would expect to see instead "Decryption failed", as defined in `age/i18n/en-US/age.ftl`.

I am not sure if this is a bug with `rage` or if I'm doing something wrong on my end. I would expect that the i18n strings defined in this crate *should* be used in my own package, but maybe that's not the case?

**Comment by str4d** [comment]
Hmm, that's unfortunate. The way you can configure the `age` library to use its localizations is with the `age::localizer()` function:

```
age::localizer().select(&requested_languages).unwrap()
```

I assumed that if a downstream library or binary didn't do this, it would simply default to the fallback language `en-US`. I guess that's not the case. I'll see if I can figure out what's going on here; more than likely I can do something to the lazy static.

Quick question: does the behaviour you see differ between debug and release builds? I know that changes how the localization library looks up the translation files, so it could also be a factor here.

**Comment by gpanders** [comment]
Unfortunately, it appears to happen in both debug and release builds.
