### ISSUE TITLE
Yubikey support

### ISSUE THREAD

**Issue by str4d** [str4d/rage#16]
Some people store their RSA SSH private keys on a Yubikey, and it would be great if we could decrypt messages encrypted to these keys (which could happen quite easily if a message is encrypted to `github:USERNAME`).

This specifically requires figuring out whether we can access RSA-OAEP decryption on a Yubikey. I have heard folk tales that it might be possible.

**Comment by str4d** [comment]
This is now far more feasible thanks to @tarcieri publishing https://crates.io/crates/yubikey-piv :heart_eyes:

**Comment by tarcieri** [comment]
Note that it's not quite ready to use... in addition to being 100% unsafe Rust, I still need to swap out the current `extern "C"` calls which link to libscard with something like the [`pcsc` crate](https://crates.io/crates/pcsc)

**Comment by str4d** [comment]
This has now been broken out into an age plugin: https://github.com/str4d/age-plugin-yubikey
