### ISSUE TITLE
Default scrypt work factor 18 is incredibly slow with WASM and i5-10210U CPU @ 1.60GHz

### ISSUE THREAD

**Issue by kanru** [str4d/rage#191]
## Environment

* OS: Debian unstable, Firefox Nightly
* rage version: main branch

## What were you trying to do

Using passphrase encryption with rage compiled to WASM

## What happened

I build a wasm wrapper around age https://github.com/kanru/rage-wasm

When runnning the test on my laptop

```
wasm-pack test --release --firefox
```

The passphrase tests take more than 1 minutes to run. I think my CPU is about average but definitely not old, which I think probably means work factor 18 is going to be also very slow for less powerful device.

The reason it is using 18 is because there is no `SystemTime::now()` support, so I hooked up performance timer with `web-sys` and it turns out my work factor is 14. The base took about 100 ms to run. I feel the speed is acceptible maybe up to work factor 16.

I'll send a PR for enabling web-sys feature.

**Comment by str4d** [comment]
Thanks for the PR!

In case you weren't aware, there is a WASM package for `rage` here: https://github.com/str4d/wage (I should add this to the README!) It uses `ReadableStream` and `WritableStream` to provide the same kind of interface as the `age` crate. I'm not a JavaScript developer though, so IDK if it's actually useful as currently built, or if the standalone-function API you're using is more familiar to JS developers, so if you have feedback LMK 🙂

**Comment by kanru** [comment]
I didn't know the `wage` package until this morning! My use case currently only need to use `&[u8]` so I build the wrapper and intend to switch to more featureful WASM package in the future. It seems `wage` might be the crate! I'll definitely take a look.

**Comment by str4d** [comment]
Yeah, it would definitely be useful to have APIs to just encrypt and decrypt byte arrays rather than requiring streams. In the meantime, let's get this issue closed 😄
