### ISSUE TITLE
StreamReader doesn't compute SeekFrom::End(0) offsets correctly

### ISSUE THREAD

**Issue by oconnor663** [str4d/rage#196]
After calling `reader.seek(SeekFrom::End(0))`, subsequent reads shouldn't return any bytes. But when I test this on a plaintext that's exactly a multiple of the chunk size, the next read actually does return bytes, as in this example:

```rust
use std::io::prelude::*;
use std::io::SeekFrom;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let plaintext: Vec<u8> = vec![42; 65536];

    // Encrypt the plaintext just like the example code in the docs.
    let key = age::x25519::Identity::generate();
    let pubkey = key.to_public();
    let encryptor = age::Encryptor::with_recipients(vec![Box::new(pubkey)]);
    let mut encrypted = vec![];
    let mut writer = encryptor.wrap_output(&mut encrypted)?;
    writer.write_all(&plaintext)?;
    writer.finish()?;

    // Seek to the end of the plaintext before decrypting.
    let cursor = std::io::Cursor::new(&encrypted[..]);
    let decryptor = match age::Decryptor::new(cursor)? {
        age::Decryptor::Recipients(d) => d,
        _ => unreachable!(),
    };
    let mut reader = decryptor.decrypt(std::iter::once(
        Box::new(key.clone()) as Box<dyn age::Identity>
    ))?;
    reader.seek(SeekFrom::End(0))?;

    // BUG: Reading should return no bytes, because we're already at EOF. However, it actually
    // returns 16 bytes.
    let mut buf = Vec::new();
    reader.read_to_end(&mut buf)?;
    dbg!(buf.len());
    eprintln!("{:?}", buf);

    Ok(())
}
```

When I run that code, here's what I see:

```
[src/main.rs:31] buf.len() = 16
[42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42]
```

I think the underlying problem comes from [this line](https://github.com/str4d/rage/blob/9f96c9c076af760730b189a7973036d96533b928/age/src/primitives/stream.rs#L534) in the `age` crate:

```rust
let num_chunks = (ct_end / ENCRYPTED_CHUNK_SIZE as u64) + 1;
```

If I understand correctly, the issue there is that `ct_end` is the total length of the ciphertext stream, and that includes the header length, which this line isn't taking into account. The result is that, when the ciphertext is equal to or slightly shorter than an exact multiple of the chunk size, this line overestimates the number of chunks by one, and thus underestimates the plaintext length by one auth tag (16 bytes).

I haven't tried fixing this myself, but looking ahead I think there's going to be another issue to sort out once this one is fixed. If the plaintext is an exact multiple of the chunk size, and I seek directly to the end, then I think the current seek logic will skip over the final chunk rather than decrypting it. As a result, I think `is_complete()` is going to keep returning `false`, which means the next read (which should successfully return no bytes) is actually going to fail. That said, I haven't tried this myself.

**Comment by str4d** [comment]
Good catch, thanks! Not sure what I thought I was doing there; it should have been ceiling division.

> looking ahead I think there's going to be another issue to sort out once this one is fixed.

I ran into this issue just before I noticed you'd noted it 😄

Fixed in #197.
