### ISSUE TITLE
UX: armor module not documented on docs.rs

### ISSUE THREAD

**Issue by Roguelazer** [str4d/rage#209]
## What were you trying to do

Upgrade a test application from rage 0.4 to rage 0.5

## What happened

ascii armoring was removed from the default feature set and the `armor` module is not documented on docs.rs. It would be nice to have the docs built with that feature so that users don't have to run `cargo doc` locally, since I imagine pretty much every user of the crate needs ascii armoring.

**Comment by str4d** [comment]
I assumed that docs.rs rendered with `doc_cfg` by default, but it turns out I need to manually enable it. Thanks for noticing!
