### ISSUE TITLE
UX: Option to accept passphrase from an external program / file descriptor

### ISSUE THREAD

**Issue by figsoda** [str4d/rage#215]
## What were you trying to do

Accept passphrase from an external program / file descriptor, e.g. `zenity`, similar to `-pass file:<(zenity --password)` option in `openssl`

**Comment by str4d** [comment]
I just finished a long UX discussion about this and other passphrase-related topics (https://twitter.com/FiloSottile/status/1401578831836856325), and the outcome is that we aren't going to support scriptable passphrase inputs natively in our CLI apps. The alternatives:

- We will add native support for passphrase-encrypted age identities. Then encryption can be scripted (using the age recipient).
- We've ensured that the [plugin system](https://hackmd.io/@str4d/age-plugin-spec) is flexible enough to support a plugin that _does_ handle passphrases in alternative ways (e.g. from a file descriptor). Given that a plugin _is_ an external program (invoked by `age`/`rage`), it can do whatever it wants to obtain the necessary information.
