### ISSUE TITLE
UX: Unable to feed password in via stdin to read_secret() in age crate

### ISSUE THREAD

**Issue by kellpossible** [str4d/rage#216]
the `age` crate's [`read_secret()`](https://github.com/str4d/rage/blob/c9ebf3cf17585f18b87a5f52a09479545638882c/age/src/cli_common.rs#L104) function mentions the following in its docs:

> If a `pinentry` binary is available on the system, it is used to request the secret.
> If not, we fall back to requesting directly in the CLI via stdin.

I assumed that I could feed the password in via stdin if pinentry is not present, but it doesn't appear to work that way, and instead uses `rpassword`'s [`read_password_from_tty()`](https://docs.rs/rpassword/5.0.1/rpassword/fn.read_password_from_tty.html). Perhaps I'm misunderstanding something?

## What were you trying to do

feed the password in via stdin

## What happened

nothing, it displayed the password prompt as per usual

**Comment by str4d** [comment]
That is a documentation error. Sorry! 😅

Passphrase encryption is intended for use by human users, not programmatically (the latter is better served by native age identities). I obviously can't enforce this in the main `age` library itself (other GUIs need a way to decrypt with a passphrase they obtained from a user), but the `age::cli_tools` module contains components I want to share across the multiple `rage` CLI tools, and there I do enforce that a user is present. Thus if pinentry is not available, the TTY is queried (which does use stdin under the hood I believe, hence the restriction on combining passphrase decryption with piping the age cipher text in).

I'll have a think about whether `age::cli_tools` should be moved into a separate crate to make the delineation clearer (or maybe directly into `rage` and shared by manually reusing the module file). In the meantime, I'll get the documentation fixed 🙂
