### ISSUE TITLE
Unicode feast in time of COVID19 plague

### ISSUE THREAD

**Issue by sergeevabc** [str4d/rage#219]
Windows 7, rage 0.5.1

[?] marks are related neither to the chosen console font, nor to the code page (866, 1251, 65001).
0.4.0 was the last one w/o them. Consider figuring out who’s responsible for this freaking decoration.

![](https://i4.imageban.ru/out/2021/04/02/bf38739866e414da13292e4a0a0ada5a.png)

**Comment by str4d** [comment]
In `rage 0.5.0` I added support for translations; as part of that, I extracted these usage info strings so they could be translated. The [?] marks correspond to this section of the strings:

https://github.com/str4d/rage/blob/46822abef5c4b833cfb3163171ef6ae8a1cd1819/rage/i18n/en-US/rage.ftl#L34-L41

I think I know how to solve this...

**Comment by str4d** [comment]
Hmm, interesting. I opened #220 thinking that would fix the problem, but it just added missing whitespace. I then noticed that the [?] marks perfectly surround every variable substitution in this multi-line translation string (beyond what OP captured in their screenshot).

**Comment by str4d** [comment]
Yeah, the bug is almost certainly somewhere inside this macro:

https://github.com/str4d/rage/blob/46822abef5c4b833cfb3163171ef6ae8a1cd1819/rage/src/bin/rage/main.rs#L440-L451

which means it's very likely an `i18n-embed-fl` bug.

**Comment by str4d** [comment]
```
>>> a = '  ⁨C:'
>>> a.encode()
b'  \xe2\x81\xa8C:'
>>> b = 'OUTPUT.⁩'
>>> b.encode()
b'OUTPUT.\xe2\x81\xa9'
```

**Comment by str4d** [comment]
Looks like these might be [First Strong Isolate](https://www.compart.com/en/unicode/U+2068) and [Pop Directional Isolate](https://www.compart.com/en/unicode/U+2069).

**Comment by str4d** [comment]
Aha, looks like this is https://github.com/kellpossible/cargo-i18n/issues/44, which points me to [`fluent::bundle::FluentBundle::set_use_isolating`](https://docs.rs/fluent/0.15.0/fluent/bundle/struct.FluentBundle.html#method.set_use_isolating):

> When formatting patterns, `FluentBundle` inserts Unicode Directionality Isolation Marks to indicate that the direction of a placeable may differ from the surrounding message.
>
> This is important for cases such as when a right-to-left user name is presented in the left-to-right message.
>
> In some cases, such as testing, the user may want to disable the isolating.

The FSI and PDI marks were introduced in [Unicode 6.3.0](https://www.unicode.org/reports/tr9/tr9-29.html) in 2013, and Microsoft [does appear to use them in its own apps](https://github.com/microsoft/calculator/issues/504), so IDK why its terminals won't render them correctly by default (i.e. not at all). For now I guess I can just turn them off (which `i18n-embed` enabled as a fix for the above-linked issue), but I'd prefer to find a solution that works for RTL languages.

**Comment by str4d** [comment]
(in fact, for most of the substitutions we _do_ want these marks to be inserted for RTL languages, since what we are inserting is usually commands that must be LTR).

**Comment by str4d** [comment]
Decided that since we don't have any RTL translations yet, I'll just turn off the marks for now, and we can revisit this either when we add RTL languages, or when Microsoft finally gets modern Unicode support into their default terminals.

**Comment by sergeevabc** [comment]
@str4d, Rage (or Age for that matter) is [far from being an intuitive security solution][1] per se and has all chances to end up like PGP. At first, I would make sure that it is convenient to use the app at least in the English-speaking world, so as not to upset the rest.

[1]: https://github.com/FiloSottile/age/issues/191#issuecomment-798914211

**Comment by str4d** [comment]
@sergeevabc I looked at your comment you linked above, and I'm not impressed. Please understand that both this and `age` are unpaid side projects; as developers we are under no obligation to do anything for anyone.

Suggestions are also far more likely to be considered when conveyed with a positive tone. Take this issue, for instance: the cause of the symbols you were seeing was my conscious and explicit work to make `rage` a more accessible and user-friendly tool (by adding translations, something few if any Unix tools have). Yet as soon as I solved your issue, instead of any kind of thanks, you point to a comment of yours that belittles the usability efforts we are actively making on `age` tooling. It really doesn't engender any desire to work on future issues you might open, and frankly discourages me from spending my evenings and weekends on this.

**Comment by sergeevabc** [comment]
@str4d, make no mistake, it’s not _my_ issue you solved, it’s _your_ slipshod job I was kind enough to report before the project got buried [by the community][1], which is less tolerant to the modern digital pollution. Developing anything in a spare time is up to you, but when it becomes shared, expect to process various feedback, not exclusively flattery and servile requests, because there is a certain level of expectations set by the achievements of ancestors. It includes bashing, because there are more and more quitters who fuel expectations but fail to deliver. When you state “a simple, modern and secure encryption tool” on the front page, you’re expected to put your money where your mouth is and not to retreat to the bushes with an offended grimace and “no obligation” mumbling once your feathers are stroked the wrong way. To fulfill that promise, the concept of simplicity should be studied properly in the first place — what does average Joe believe is simple based on the experience of using other tools? Translation is hardly the right answer when a user can’t even start using the app because it’s divided in two pieces. Think it over instead of defending your undervalued ~evenings and weekends~ ego if you really care about lack of proper security in particular and society development in general.

[1]: https://news.ycombinator.com/item?id=1123364

**Comment by str4d** [comment]
Congratulations, you've earned yourself a block from me. Have a lovely time "bashing" "quitters".
