### ISSUE TITLE
Encrypted age identities

### ISSUE THREAD

**Issue by str4d** [str4d/rage#235]
Currently, the `-i` flag supports two kinds of files:

- An SSH key file containing a single (possibly-encrypted) key.
- An identity file containing multiple age identities (native and plugin), one per line.

In a [long UX discussion](https://twitter.com/FiloSottile/status/1401578831836856325) with @FiloSottile and @benjojo, we decided to add native support for a third kind of file: an age identity file that is itself encrypted with age using a passphrase.

## Format

Exactly what is produced by `rage -p -o key.age <(rage-keygen)`

- `rage-keygen` will not offer to encrypt identities itself; this will be a manual step.

## UX flow

- Given `rage -d -i key.age ... ciphertext.age`, `rage` will attempt to parse the file as an age ciphertext.
  - If that fails, continue parsing as currently.
- If the file is not encrypted to a single scrypt recipient (as currently required for `-p`), exit with an error message.
- Otherwise, store the file in an `age::Identity` implementation with a callback that will request a user passphrase.
- Once we get to the decryption step that tries this identity, request the passphrase and try to decrypt `key.age`.
- If decryption succeeds, parse the contents of the file as an age identity file (containing native and plugin identities).
  - If parsing fails, exit with an error message.
- Try each contained identity in turn against `ciphertext.age`.
  - If none of the identities contained in `key.age` can be used to decrypt `ciphertext.age`, print a warning containing an apology (that we asked for a passphrase that was wasted) and an explanation.

**Comment by FiloSottile** [comment]
> Note that we do not continue with the contents of later -i flags; this is a hard failure, since we need to teach the user how these work.

I would make it just a warning to explain what’s going on, but otherwise behave like it was an unencrypted identity file and carry on.

Requesting a useless password is a UI annoyance, so we should apologize in the UI, but not change the semantics.

**Comment by str4d** [comment]
That's reasonable; as long as the user understands what is going on, I'm happy. We can continue to make use of `stderr` for conveying this, as we do for other warnings.
