### ISSUE TITLE
UX: Better recipient support to match reference implementation

### ISSUE THREAD

**Issue by uhthomas** [str4d/rage#265]
## What were you trying to do

Encrypt for recipients listed via GitHub or HTTP(S) resources. The spec, [age v1](https://age-encryption.org/v1), has many examples of using recipients like `github:<username>` or providing a HTTP URL. This doesn't work with rage 0.6.0.

## What happened

```sh
❯ rage -r github:uhthomas test.txt
Error: Invalid recipient 'github:uhthomas'

[ Did rage not do what you expected? Could an error be more useful? ]
[ Tell us: https://str4d.xyz/rage/report                            ]
❯ rage -r https://github.com/uhthomas.keys test.txt
Error: Invalid recipient 'https://github.com/uhthomas.keys'

[ Did rage not do what you expected? Could an error be more useful? ]
[ Tell us: https://str4d.xyz/rage/report                            ]
```

**Comment by mihaigalos** [comment]
Not sure if this is a separate issue or you want to consolidate it as part of this one:

Any plans to enable recipient removal from already encrypted files?
Specifically, when used with a YubiKey-hosted identity and that YubiKey gets lost/stolen?

**Comment by AlexCzar** [comment]
This issue should probably be closed, as age removed the functionality as well.
![image](https://github.com/str4d/rage/assets/1010298/bf793c5c-d93f-489c-bdd2-58d3b35066b9)

**Comment by str4d** [comment]
Closing as stale:
- The age spec has not mentioned GitHub or HTTPS recipients in a long time.
- `age` has error handling for `github:` recipients. `rage` doesn't, and I haven't had any other questions about `github:` being unsupported, so I'm not going to add error handling.
