### ISSUE TITLE
Missing arm64 debian binary for 0.7.1

### ISSUE THREAD

**Issue by dpeukert** [str4d/rage#286]
Hey, I've noticed that the `rage_0.7.1_arm64.deb` binary is missing from the [latest release](https://github.com/str4d/rage/releases/tag/v0.7.1). Looks like the build timed out on `cargo install`: https://github.com/str4d/rage/runs/4638575525

**Comment by str4d** [comment]
Gah, that's probably due to crates.io timeouts, which I've been encountering regularly in recent weeks. I can't rerun the release workflow as that will overwrite all of the successful binaries, so I'll figure something out locally.

**Comment by str4d** [comment]
I ended up not having time to figure something out, but the `0.8.0` workflow has run successfully.
