### ISSUE TITLE
On docs.rs, reports `rage-0.7.1` is not a library.

### ISSUE THREAD

**Issue by percy507** [str4d/rage#293]
Hi @str4d ,

Thanks for your work.

It seems rage build failed on `docs.rs`. But after searching, I find there also exist a package named `age`, I wonder which one should I use?

> https://docs.rs/crate/rage/0.7.1

<img width="1235" alt="image" src="https://user-images.githubusercontent.com/18365078/156893401-e9d65081-d831-4e13-b8c6-f6841e9e81c7.png">

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/18365078/156893469-eca9a5ed-c6a0-435a-aa60-9fcfb9e019b0.png">

**Comment by str4d** [comment]
`rage` is the CLI tool; `age` is the Rust library backing it.

**Comment by percy507** [comment]
Thanks for the clarification.
