### ISSUE TITLE
Threshold encryption

### ISSUE THREAD

**Issue by selfuryon** [str4d/rage#323]
This is a feature request.
Currently, rage can encrypt the same file key (which used as the key to encrypt the file) with several recipients.
How about add to possibility to encrypt/decrypt with threshold cryptography: for example, use Shamir for dividing file key between several recipients, so we need several recipients to decrypt a box?

**Comment by str4d** [comment]
This could definitely be implemented as an age plugin!

**Comment by p2p-sergey-y** [comment]
Ok, I'll try to do that
