### ISSUE TITLE
UX: weird unknown gui pops up when using cli

### ISSUE THREAD

**Issue by DianaNites** [str4d/rage#336]
## What were you trying to do

Encrypt a file with a passphrase

## What happened

instead of prompting for my passphrase in the terminal like I expected from a cli tool, it opened a GUI prompt.

Investigation shows this is related to something called pinentry, which has no way to be disabled except by making PATH empty? Which *doesn't work*, because.. then `rage` cant be found. Having to rewrite or construct a new PATH only pointing to `rage`, on the fly, or only use the absolute path, every time I want to use it, is just completely unacceptable.

`pinentry` apparently lives in `/usr/bin` and is a transitive dependency of `gnupg`, which itself is a transitive dependency of `pacman`, meaning it will always exist on Arch, and likely many other linux distros, and I as a user have no control over this.

More generally, rage is a command-line tool, and i do not expect such tools to open GUI windows unless explicitly told to, let alone ones from insecure legacy programs like gpg, and especially not when this behavior is documented *nowhere*, an open issue which has existed since 2021, #280.

This is not the behavior I expected at all

```
rage -p some_file -o some_file.age
```

**Comment by pepa65** [comment]
Not sure if a regression occurred, but with `$PINENTRY_PROGRAM` being empty, and `export PINENTRY_PROGRAM`, still `rage 0.11.1` uses a GUI popup here.
