### ISSUE TITLE
Bash completion files

### ISSUE THREAD

**Issue by str4d** [str4d/rage#35]
... would be very good for usability!

**Comment by msfjarvis** [comment]
Seems like [clap](https://github.com/clap-rs/clap) can generate completion files but `structopt` compatibility still hasn't landed so there's non-trivial effort involved in migrating entirely to clap. If that's something that you're going to be okay with then I can spin up a PR soon enough.

P.S. What's your goal w.r.t. CLI interop with the reference age client? I did [this](https://github.com/msfjarvis/rage/commit/9a8fb2a767a1ff9367a3abc4caaa8d8cbfdc2ec9) to make keygen output match `age` but I wanna be sure that's helpful to this project before start a PR.

**Comment by str4d** [comment]
I decided against clap for this project because its complexity wasn't warranted for this relatively simple and stable API. Similarly here, my thinking is that we can figure out the completion files once, and then not have to worry about them again (only rage-keygen is likely to grow more options, for e.g. handling hardware keys).

Re: compatibility, my intent is for them to be interchangeable as much as possible, although specific differences will be handled on a case-by-case basis.
