### ISSUE TITLE
How To Sign Blobs With Age Keypairs?

### ISSUE THREAD

**Issue by bonedaddy** [str4d/rage#358]
Hello, I'm looking to sign blobs of data with  the age keypairs generated through `rage`, however unless I'm missing something, it doesnt seem possible to do this?

Any links to docs or examples would be appreciated.

**Comment by str4d** [comment]
If you're using `rage-keygen` then you are generating native age identities, which are X25519 secret keys. You cannot use them directly as signing keys, but it is possible to convert them into one part of an Ed25519 key. The details get complicated though by the usual structure of Ed25519 keys. See [this blog post](https://words.filippo.io/using-ed25519-keys-for-encryption/) for details about the reverse direction (that we use in age), which has a bit more information about X25519-to-Ed25519 and links to some other resources.
