### ISSUE TITLE
PBE default work factor can cause OOM issues on memory-constrained environments

### ISSUE THREAD

**Issue by tekul** [str4d/rage#383]
I'm using PBE within a  webapp to encrypt data on a per user basis. This appeared to work Ok, but I noticed my app was dying with an OOM error when I deployed it to fly.io. Further investigation shows that a single scrypt-based encryption is using over 500Mb which seems to be the cause. I've created [a repo](https://github.com/tekul/age-test) with the code I used to test the issue and added the output from heaptrack

![heaptrack](https://user-images.githubusercontent.com/191720/235452993-64a18d40-9625-4f7e-963a-9450c210c7b7.png)

I would like to be able to limit or set the work factor to cap memory usage - I notice there was a previous PR, #334, which did this, so I can create a fork along similar lines and use that with hard-coded values. 

You mentioned a necessary refactor due to plans in the Go implementation to change PBE. Do you have a reference or a link for that? I realise there are different expectations between using a CLI to encrypt files and an API in an app, but it would be nice to have more control in the latter case since I have no control over how the work-factor is assigned on the cloud-based system and the performance-based work-factor estimate will also have an impact on the memory used.

**Comment by str4d** [comment]
The refactor is #504.

**Comment by str4d** [comment]
The refactor was completed in #507, and there's now an `age::scrypt::Identity` that has a `set_max_work_factor` method (replacing the previous argument to passphrase-based decryption). I'll add an equivalent `set_work_factor` method to the new `age::scrypt::Recipient` type, enabling library-based workflows to override the default (the `rage` CLI app, and the existing `Encryptor::with_user_passphrase` method, will remain unconfigurable in this regard).
