### ISSUE TITLE
Add a `run_identity_state_machine` for identity-only plugin implementations

### ISSUE THREAD

**Issue by str4d** [str4d/rage#387]
https://github.com/C2SP/C2SP/pull/5#discussion_r1059560476

**Comment by str4d** [comment]
Instead of adding a new function, I'm making the state machine arguments to `run_state_machine` optional.

**Comment by emilazy** [comment]
Thanks! Does it make sense to have a recipient-only plugin? I guess if you want different identity backends for that recipient type?

**Comment by str4d** [comment]
Perhaps, or maybe a corporate environment where they use separate plugins for encryption and decryption. In any case it was easy to generalise for minimal UX complexity.
