### ISSUE TITLE
Re-enable ~/.config/age/keys.txt

### ISSUE THREAD

**Issue by str4d** [str4d/rage#39]
I accidentally disabled it by requiring an `-i/--identity` parameter while improving error messages. This error message should instead only be returned if there are no `-i/--identity` parameters *and* no `keys.txt` config file.

**Comment by sts10** [comment]
I'm having some trouble with this in v 0.6.0. I confirmed that my age key is in `~/.config/age/keys.txt`. I then encrypt a file with:
```
rage -i ~/.config/age/keys.txt -e -o encrypted.txt secrets.txt
```

I thought I'd be able to decrypt this file with `rage -d encrypted.txt`, but I get an error: 
```
Error: Missing identities.
Did you forget to specify -i/--identity?
```

`rage -i ~/.config/age/keys.txt -d encrypted.txt` does work: it prints the contents of secrets.txt to the terminal.

I'm using Ubuntu 20.04.2 LTS.

**Comment by str4d** [comment]
Support for a default identity path was removed in rage 0.5.0 (and similarly in age), as we reached the conclusion that identities should be context-specific. As you correctly surmise, you can still pass the old path to rage directly to decrypt with those identities.

**Comment by str4d** [comment]
Specifically, it was removed in https://github.com/str4d/rage/pull/152.

**Comment by sts10** [comment]
Gotcha. Thanks for info, and your work!
