### ISSUE TITLE
Is there any way of signing the message?

### ISSUE THREAD

**Issue by PaulDotSH** [str4d/rage#397]
Hi, I want to use this with kleopatra to sign and encrypt a message for a recipient, is there any way to do this?

## Environment

* OS: Linux
* rage version: N/A

## What were you trying to do
Encrypting and signing a message for a recipient
## What happened
Missing API

**Comment by str4d** [comment]
No, `rage` only implements the age encryption format and does not include any signing capabilities. The decision on how and where to apply signatures is very context-specific, and age does not attempt to solve it. You should look at tools like `signify` or `minisign`.
