### ISSUE TITLE
UX: How to add a recipient to an existing age file?

### ISSUE THREAD

**Issue by pierreprinetti** [str4d/rage#408]
## What were you trying to do

I want to add one recipient to the recipient stanza of an existing age file, while keeping the file key.
How do I do that with the age crate?

Thank you!

**Comment by str4d** [comment]
This is not currently a supported feature of the `age` crate, as there are UX issues to resolve first, and I don't want to expose this kind of feature if it would not (at least in theory) also be exposed in the reference implementation. See https://github.com/FiloSottile/age/issues/136 for existing discussion about this.

**Comment by pierreprinetti** [comment]
Thank you for the pointer!
