### ISSUE TITLE
UX: Pronounciation

### ISSUE THREAD

**Issue by siltyy** [str4d/rage#411]
## What were you trying to do
I was talking to a friend about rage.

## What happened
I was struck by a revelation so utterly horrifying, it rattled the very foundations of my soul: If "age" is to be [pronounced](https://github.com/FiloSottile/age/blob/main/README.md?plain=1#L34) with a guttural, unyielding hard *g*, then I trembled to contemplate the fate of "rage". Does it too thunder with the ferocity and might of the hard *g*? Ever since this harrowing inquiry first clawed its way into my consciousness, it has tormented me ceaselessly, demanding a resolute, unequivocal response.

```
03:12 <silt!> oh yeah age is pretty cool too
03:12 <silt!> have you seen rage? it's a rust implementation
03:12 <silt!> wait wtf
```

**Comment by FiloSottile** [comment]
The unhingedness of cryptographers knows no limits.

**Comment by ameuret** [comment]
@siltyy I'm afraid I'm the bearer of an even more soul-shattering epiphany: it's pronunciation.

**Comment by siltyy** [comment]
> @siltyy I'm afraid I'm the bearer of an even more soul-shattering epiphany: it's pronunciation.

You have out-pedantried me, and for this, I salute you.

**Comment by str4d** [comment]
To close out this issue: I do pronounce it with a hard _g_, matching the `age` pronunciation. However, I am perfectly happy for people to rage-quit (soft _g_) other encryption tools 😄
