### ISSUE TITLE
UX: failed to fill whole buffer with ArmoredWriter

### ISSUE THREAD

**Issue by nine9ths** [str4d/rage#412]
Apologies if library issues should be filed differently, I suspect I'm just missing something (still pretty new to rust) and there's no actual bug though so this seemed more appropriate than a bug report.

## What were you trying to do

Trying to use ArmoredWriter to create an ASCII representation of encoded data. I modified the examples from the documentation to use ArmoredWriter and ArmoredReader:

```
        use age::armor::{ArmoredReader, ArmoredWriter, Format};
        use age::secrecy::Secret;
        use std::io::{Read, Write};

        let plaintext = b"Hello world!";
        let passphrase = "this is not a good passphrase";

        // Encrypt the plaintext to a ciphertext using the passphrase...
        let encrypted = {
            let encryptor =
                age::Encryptor::with_user_passphrase(Secret::new(passphrase.to_owned()));

            let mut encrypted = vec![];
            let mut writer = encryptor
                .wrap_output(
                    ArmoredWriter::wrap_output(&mut encrypted, Format::AsciiArmor).unwrap(),
                )
                .unwrap();
            writer.write_all(plaintext).unwrap();
            writer.finish().unwrap();

            encrypted
        };

        println!("{}", String::from_utf8(&encrypted).unwrap());

        // ... and decrypt the ciphertext to the plaintext again using the same passphrase.
        let decrypted = {
            let decryptor = match age::Decryptor::new(ArmoredReader::new(&encrypted[..])).unwrap() {
                age::Decryptor::Passphrase(d) => d,
                _ => unreachable!(),
            };

            let mut decrypted = vec![];
            let mut reader = decryptor
                .decrypt(&Secret::new(passphrase.to_owned()), None)
                .unwrap();
            reader.read_to_end(&mut decrypted).unwrap();

            decrypted
        };

        assert_eq!(decrypted, plaintext);
```

## What happened

Running this code results in the following panic `Io(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" })`

I can also see that the println only prints `-----BEGIN AGE ENCRYPTED FILE-----`

Any advice is much appreciated. Thanks!

**Comment by str4d** [comment]
Your problem is with this line:
```rust
            writer.finish().unwrap();
```

This finishes the encryptor, and then drops the `ArmoredWriter` before finishing it. The latter is necessary because `ArmoredWriter` internally buffers data that will go into each line. Your plaintext is short enough that it all fits into a single line, so by never finishing the `ArmoredWriter`, the only line written out is the start line.

Change this line to:
```rust
    writer
        .finish()
        .and_then(|armor| armor.finish())
        .unwrap();
```
