### ISSUE TITLE
Name conflict with Rage the video player

### ISSUE THREAD

**Issue by b1ek** [str4d/rage#450]
Hello everyone!

Ive been writing a PKGBUILD for aur for this project, and i found that the name `rage` has already been taken by [this project](https://www.enlightenment.org/about-rage).

Which name should I (and possibly other packagers in the future) use to prevent conflicts and confusions? I think `rage-crypto` would be pretty simple and descriptive

**Comment by b1ek** [comment]
Just so you can see the problem, here's [the rage player package](https://aur.archlinux.org/packages/rage-git) and [the one i already published](https://aur.archlinux.org/packages/rage-bin).

For those unfamiliar with AUR, my package ends with `-bin` because it downloads a binary, and rage's ends with `-git` because it builds the code from master branch.

I think its pretty easy to mess up for an unattentive user

**Comment by b1ek** [comment]
I also just noticed that the openSUSE package uses `rage-encryption`, probably because of this problem. Maybe it would make sense to enforce it on future packagings?

**Comment by str4d** [comment]
Yeah, the openSUSE naming conflict was discussed in #210, and `rage-encryption` was the fallback package name that was used. Note however that I did not agree with renaming the binaries, so the package conflicts system for your package manager needs to be used here to prevent both being installed at the same time.

**Comment by str4d** [comment]
I've opened #451 to add specific guidance on package naming to the README, which should hopefully avoid the need for packagers to open future issues (on this topic at least).
