### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by gibbz00** [str4d/rage#470]
This is not a bug report/issue per se, but I've now begun to prepare for the first release of [`rops`](https://github.com/gibbz00/rops). It relies on the unpublished addition from https://github.com/str4d/rage/pull/429. Would great if I could point the age dependency to a set version so that I'm allowed to publish to crates.io 😊

**Comment by str4d** [comment]
I'm done with code changes for the release, and have been coordinating translations. Yesterday, I set a release date for next week, which I have configured as the milestone end date.

**Comment by gibbz00** [comment]
Banger, thanks for letting me know!

**Comment by gibbz00** [comment]
Banger, thanks for letting me know!

**Comment by str4d** [comment]
0.10.0 has been published.
