### ISSUE TITLE
Feature-parity with age: version flag

### ISSUE THREAD

**Issue by razvanazamfirei** [str4d/rage#485]
## Environment

* OS: Darwin arm64, macOS 14.4
* rage version: rage 0.10.0

## What were you trying to do
`rage -version`

`age` supports `-version`, but `rage` does not. This can cause an issue if rage is used as a drop-in for age.

## What happened

```
❯ rage -version
error: unexpected argument '-v' found

  tip: to pass '-v' as a value, use '-- -v'

Usage: rage [--encrypt] (-r RECIPIENT | -R PATH)... [-i IDENTITY] [-a] [-o OUTPUT] [INPUT]
       rage [--encrypt] --passphrase [-a] [-o OUTPUT] [INPUT]
       rage --decrypt [-i IDENTITY] [-o OUTPUT] [INPUT]```

**Comment by razvanazamfirei** [comment]
See, e.g., https://github.com/twpayne/chezmoi/issues/3551

**Comment by str4d** [comment]
You can use either `-v` or `--version` with current `rage`. `-version` will not be supported.
