### ISSUE TITLE
UX: MacPorts availability

### ISSUE THREAD

**Issue by turbocool3r** [str4d/rage#526]
It would be great if, like age, rage was available at MacPorts (a less popular package manager for Macs).

**Comment by str4d** [comment]
I know nothing about MacPorts, but I'd be happy to give pointers in this issue about how to package `rage` to someone who does.

**Comment by turbocool3r** [comment]
I've submitted a PR (https://github.com/macports/macports-ports/pull/25600) to add a port for `rage` to MacPorts, it would be nice if you could take a look. I've added myself as a maintainer, but if you'd like some other people to be included I can add them in this PR.

**Comment by str4d** [comment]
And it's live in MacPorts! Thanks 😄
