### ISSUE TITLE
Publish 0.2.0 on crates.io

### ISSUE THREAD

**Issue by fubuloubu** [str4d/rage#66]
Unsure if this is the right package, but was hoping v2.0.0 could get uploaded: https://crates.io/crates/age

**Comment by str4d** [comment]
You'll be waiting a while; I don't even have v1.0.0 out yet! 😝

Currently `rage` is in beta, for which I am using `0.X` version numbering. The next release will be 0.3.0, which will be the first release that uses the `rage` crate for the CLI tools. I'm hoping to get that out this weekend, and then continue working on the plugin system.

**Comment by fubuloubu** [comment]
@str4d whoops! I meant 0.2.0!

0.1.1 is the last one listed on crates

**Comment by str4d** [comment]
Wait, what? I thought I'd published it to crates.io! Sorry! Doing that now

**Comment by str4d** [comment]
Done! https://crates.io/crates/age/0.2.0

Thanks for letting me know!

**Comment by fubuloubu** [comment]
No problem! Will be working updating page, "now with more rage"
