### ISSUE TITLE
[FEATURE] Please create homebrew package for OSX

### ISSUE THREAD

**Issue by wakatara** [str4d/rage#81]
While I'm personally fine compiling this with cargo I've noticed adoption tends to be _much_ easier for folks on osx if you provide a homebrew package to give you something like `brew install rage` (which is both useful and hilarious as a command... 😜  )

Could we have one? (or I could take a shot at a formula for it though never done it myself.).

thanks!
Daryl.

**Comment by str4d** [comment]
I've merged a Homebrew formula that builds and installs `rage` and `rage-keygen`. See the readme for usage instructions.

I wasn't sure what to do with `rage-mount`. It's not clear to me whether that should be some kind of optional thing inside the `rage` formula, or whether there should be a separate `rage-mount` formula. I've left it out for now; if you particularly want it and/or know how this should be handled, please make a new issue.

**Comment by wakatara** [comment]
Hmmm... I just did a `brew update` but I'm not seeing it available from homebrew. And a `brew search rage` came back empty. Is there some sort of review process that is needed from the brew side before it "goes live"?

I have to admit to only using rage and rage-keygen at the moment (I also want to use it as a crate instead of gpg for a small project I am working on to replace jrnl.). I think you're most likely fine to start without rage-mount at the moment as I imagine anyone sophisticated enough to use it would be fine using cargo to build the stuff themselves.  =] 

ciao!

**Comment by wakatara** [comment]
Doh, just realized you meant merged it into the codebase rather than the Homebrew formulas available. Lemme take a look at how to get that into homebrew master (I should have figured that out long ago anyway) and go from there to help out.

**Comment by wakatara** [comment]
Did you want this available in homebrew-core or via the taps system (eg. brew tap str4d/rage ?).

**Comment by wakatara** [comment]
The formula looks good though when I attempt to brew tap I am getting errors (inconsistent with what you'd expect using other brew formulae). I think in order to take advantage of `brew tap` you need to put the formula into a repo like `str4d/homebrew-rage`. I have the following fails on this (admittedly, not having set up taps myself in the past I had to go read up on it... =] 

```
~ brew tap str4d/rage
Updating Homebrew...
==> Tapping str4d/rage
Cloning into '/usr/local/Homebrew/Library/Taps/str4d/homebrew-rage'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Failure while executing; `git clone https://github.com/str4d/homebrew-rage /usr/local/Homebrew/Library/Taps/str4d/homebrew-rage` exited with 128.
 ▲ ~ brew tap str4d/rage/HomebrewFormula
Error: Invalid tap name 'str4d/rage/HomebrewFormula'
 ▲ ~
```

**Comment by str4d** [comment]
Sorry, I said "See readme for usage instructions", but I should have copied them here:
```
brew tap str4d.xyz/rage https://str4d.xyz/rage
brew install rage
```
(I've done this the same way as @FiloSottile did his `age` formula so that the formual itself doesn't depend on GitHub.)

> Did you want this available in homebrew-core or via the taps system

I figured taps system was fine for now, as this is still technically beta software.
