### ISSUE TITLE
UX: age doesn't require -p for decryption of passphrase

### ISSUE THREAD

**Issue by southwindcg** [str4d/rage#83]
## What were you trying to do
Decrypt passphrase-encrypted file, `rage -d test.rage > test` with rage 0.3.1.

## What happened
Error: Missing identities.
Did you forget to specify -i/--identity?
You can also store default identities in this file:
    /home/user/.config/age/keys.txt

`rage -d -p test.rage > test` is successful.

From age:
> Passphrase protected files are automatically detected at decrypt time.

`age -d test.age > test` is successful. **-p** not required.

**Comment by str4d** [comment]
The reason that I was using an explicit `-p/--passphrase` for decryption was that passphrase input was clobbering piped stdin, and I wanted the latter more. During my livestream today, I was pointed to the `rpassword` crate, which provides the same cross-platform fallback but doesn't clobber stdin! So I'll be pushing changes soon that remove this requirement.

**Comment by sergeevabc** [comment]
Rage is confusing to use indeed as its help says nothing what is IDENTITY, so…
```console
-i, --identity IDENTITY    identity to decrypt with (may be repeated)

$ rage -d -i age1*** file.txt.enc > file.txt
Error: The system cannot find the file specified. (os error 2)
```

It’s ```age``` that truly helps to understand that FILE is required, not a string.
```console
-i, --identity KEY          Use the private key file at path KEY. Can be repeated.
```
Then it (silently) works as expected.
```console
 rage -d -i key.txt file.enc.txt > file.txt
```

**Comment by str4d** [comment]
Hi! This is great usability feedback 🙂 Please open a new issue for this, instead of commenting on a closed issue.
